added project
Ayush7614/Bundli-Frontend pull request #530
Opened 2022-03-01 16:53 UTC by isha614

Added a new project named- Sticky Notes

2022-03-02 12:25 UTC, Ayush7614 approved these changes

2022-03-02 12:27 UTC, Ayush7614 requested changes
@isha614 Please mention a issue that merged this PR and closed that issue

2022-03-02 17:24 UTC, isha614 commented
> @isha614 Please mention a issue that merged this PR and closed that issue

Should I mention in the  comment or somewhere else?

2022-03-02 17:25 UTC, isha614 reviewed
Added Sticky Notes Projects - Issue no. #531

2022-03-05 06:42 UTC, Ayush7614 approved these changes

2022-03-05 06:43 UTC, merged